<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eClassifiers xsi:type="ecore:EClass" name="WModel" eSuperTypes="#//WElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" lowerBound="1"
        upperBound="-1" eType="#//WElement" containment="true" eOpposite="#//WElement/model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" lowerBound="1" upperBound="-1"
        eType="#//WModelRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//WModel"
        eOpposite="#//WModel/ownedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WRef" eSuperTypes="#//WElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WLink" eSuperTypes="#//WElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//WLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//WLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" upperBound="-1"
        eType="#//WLinkEnd" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WModelRef" eSuperTypes="#//WRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElementRef" upperBound="-1"
        eType="#//WElementRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WElementRef" eSuperTypes="#//WRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="WLinkEnd" eSuperTypes="#//WElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//WElementRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationModel" eSuperTypes="#//WModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="integratedModels" lowerBound="1"
        upperBound="-1" eType="#//IntegratedModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegratedModel" abstract="true" eSuperTypes="#//WModelRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPIM" eSuperTypes="#//IntegratedModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="BDM" eSuperTypes="#//IntegratedModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPM" eSuperTypes="#//IntegratedModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Match" eSuperTypes="#//WLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="#//WLinkEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongs" lowerBound="1"
        eType="#//IntegratedModel"/>
  </eClassifiers>
</ecore:EPackage>
